	ORG	0300H
mydata:	DB	3FH, 06H, 5BH, 4FH, 66H, 6DH, 7DH, 07H, 7FH, 6FH

        ORG     0000H
	MOV	R6, #0AH
	MOV	A, #0H
	MOV	R3, #0H
FIRST:
	MOV	A, R3
	MOV	DPTR, #mydata
	MOV	R7, #0AH
	MOVC	A, @A+DPTR
	MOV	B, A
	MOV	P0, B		; FIRST LED
SECOND:	CLR	A
	MOVC	A, @A+DPTR
	MOV	P1, A		; SECOND LED
	INC	DPTR
	ACALL	delay
	DJNZ	R7, SECOND
	INC	R3
	DJNZ	R6, FIRST

DELAY:	MOV	R0, #1
	MOV	R2, #1
SAME:	DJNZ	R2, SAME
AGAIN:	DJNZ	R0, AGAIN
	RET
	END

