; 8051 PROGRAM TO BLINK LED EVERY 1 SECOND
ORG 0000H
MOV TMOD, #01H ; SELECT TIMER 0
; wont delay for 1 sec haha...
lOOP: MOV TL0, #68H     
      MOV TH0, #0FCH

      CPL P0.0
      ACALL DELAY
      SJMP LOOP

DELAY:SETB TR0 ; START THE TIMER
SAME: JNB TF0, SAME
      CLR TR0
      CLR TF0
      RET
END
